### ISSUE TITLE
Tooltip links with anchors or searches

### ISSUE THREAD

**Issue by vaniwiki** [zioth/dokuwiki-autotooltip#11]
I have lots of links that jumps to paragraph anchors, and/or have predefined searches, like this:

`[[books:bg:13:8-12#id3?s=absolute+truth|Bg. 13.8-12]]`

All my regular links give tooltips, but not these ones. I'm not sure if this is intentional, but I would love to have mine styled with popovers! :)

**Comment by vaniwiki** [comment]
Also, relative links doesn't make a tooltip, but I would prefer to keep it that way. I can see why links with searches in them probably shouldn't be a link. But it would still be nice. :)

**Comment by zioth** [comment]
I agree. Links that go to other pages should have tooltips, even if they include anchors or searches. Ideally, an anchor link would preview the text at that anchor, but that's not possible without a huge performance hit.

If I don't implement this in the next few weeks, feel free to bug me. :)

**Comment by vaniwiki** [comment]
> Ideally, an anchor link would preview the text at that anchor, but that's not possible without a huge performance hit.

I thought about this as well, as my anchors use the purplenumbers plugin and links to paragraphs. And similarly my thought was that this will be a performance issue. But I am happy with only meta description display in my case; I don't see tooltips with anchor text improving the presentation.

I still need a way to try and combine the purplenumbers and autotooltip plugin renderers, as I can currently only use one of the functions at one time. Autotooltip has taken over by sheer usefulness after I populated yet another 30.000 pages with meta description, yet purplenumbers is crucial to my latest undertaking of making a digital index, with links that jump to the actual paragraph and highlights a search phrase. Together they will be amazing! :)

**Comment by zioth** [comment]
You could merge the two plugins manually. That's relatively easy for renderer plugins, but it's still a pain. You could also write your own action plugin to do post-processing on the final HTML. Or wait for the multiple-renderer plugin to work correctly. :)

**Comment by zioth** [comment]
Or... depending on how often you use purplenumbers, you could replace it with the very simple `anchor` plugin I wrote years ago. You'd have to create an anchor for every place you want to link to.

**Comment by zioth** [comment]
Fixed.

**Comment by vaniwiki** [comment]
Ouch! After updating, I lost my anchor links with unspecified link names. Does that make sense? For ex. [[glossary:a#Abduction]] now only displays `a` and not `Abduction`, as it did previously.

**Comment by zioth** [comment]
Are you sure that ever worked? When I disable the plugin, I see the same thing you're describing.

**Comment by vaniwiki** [comment]
Could be this issue evaded me in previous releases, as I only started using it recently. But with the xhtml renderer (as well as purpleplugin renderer) I get anchor names. I could specify link names manually, of course, I just thought it was related to this recent change and easy to fix. :)

**Comment by vaniwiki** [comment]
Nice! Works perfectly. I appreciate your swift response and action. 🥇

**Comment by zioth** [comment]
It works? Not sure why, since yesteday's fix should only affect links that _don't_ have tooltips, but I'm happy it worked. :)

**Comment by vaniwiki** [comment]
Yes, those links do not have tooltips. But I still need them. :)

**Comment by zioth** [comment]
Ok. Good to know the fix you saw was the fix I made, then. :)
