### ISSUE TITLE
Tooltip severely squashed

### ISSUE THREAD

**Issue by vaniwiki** [zioth/dokuwiki-autotooltip#12]
...when hovering over a link on the right side of the screen. Maybe possible to do something like this: https://popper.js.org so that the direction of the tooltip changes?

**Comment by zioth** [comment]
Fixed. I also fixed an issue where, at narrow widths, the tooltip could temporarily extend off the screen.

**Comment by vaniwiki** [comment]
Beautiful! 🥇 Do you have a sponsor program going yet? :)

**Comment by zioth** [comment]
Happy to help.

I've thought of setting up some kind of donation system, but it's hard to imagine making more than a couple dollars a month off of it, so I haven't bothered. :)
