### ISSUE TITLE
Tooltip code showing up in Google search

### ISSUE THREAD

**Issue by vaniwiki** [zioth/dokuwiki-autotooltip#13]
Is there a way to prevent Google from indexing the tooltip code?

**Comment by zioth** [comment]
Yes there is. Not sure how well it works with other search engines, but this is easy to fix, and it's fixed.

Good catch. These tooltips could really mess up google indexing, with content from a bunch of pages squished together.

You should see results within a couple weeks, when Google gets to re-indexing your pages.

**Comment by vaniwiki** [comment]
Excellent! Well, it was on a chance encounter with Google search that showed hits from my site. Thanking you for the quick turnaround. Now, if only Google would be as quick... :)
