### ISSUE TITLE
Tooltip breaks links when the nspages plugin is used. 

### ISSUE THREAD

**Issue by ExploratorV** [zioth/dokuwiki-autotooltip#19]
Hi, I encountered a conflict with this plugin: https://www.dokuwiki.org/plugin:nspages

If nspages is used at tooltip range, the links become broken (should be a single line of links): 
![image](https://user-images.githubusercontent.com/127654458/224706293-94a5f789-a63f-4914-9347-66073c34b074.png)

It seems like it's trying to paste the namespace tree provided by the nspages plugin.

**Comment by zioth** [comment]
I just tried it and it seemed to work. The llinks created by nspages even had tooltips from autotooltip.

Could you give me some more details on your nspages and autotooltip configuration? And do you also have autolink4 installed?

**Comment by zioth** [comment]
Closing this for now. If you can provide more details, feel free to reopen!
