### ISSUE TITLE
Tooltip won't hide on fast mouse moves

### ISSUE THREAD

**Issue by barredespace** [zioth/dokuwiki-autotooltip#20]
Thank you for this plugin, very useful.
Just one small problem I couldn't fix on my own : when moving fast over a link, the tooltip will still display even if the mouse pointer is not over the link anymore. The only way to make it disappear is to move over the same or another AutoToolTip enabled link.
Tried this with different browsers with default AutoToolTip configuration, same problem.

**Comment by zioth** [comment]
Which browsers and operating system did you see this on? I'm not able to make it happen.

**Comment by barredespace** [comment]
Mac OS 12.7 (Monterey) / latest Vivaldi (chromium based), Safari, Chrome, Firefox.

I thought it may not be related to mouse speed but rather to the page layout because I'm using indexMenu with lots of links stacked on the same page, but I just tried it on a normal page, with just few links and it does the same.

Here is a [short video capture](https://imgur.com/a/uPgWbBQ).

**Comment by zioth** [comment]
That video is very helpful. I think it has to do with the interaction between autotooltip and your template.

Which template are you using? And could I have a link to that page so I can play with it myself?

**Comment by barredespace** [comment]
Thank you.
I am using [Notos](https://www.dokuwiki.org/template:notos)
The website is in beta phase but you can access it [here](https://beta.planete-vivante.fr/)

**Comment by zioth** [comment]
I see the bug on your site, but not mine. However, I don't see any way the template could be causing it.

In any case, I found a timing issue in my code. Give it a try. I hope it helps!

Also, you mentioned that this was the only thing you couldn't fix on your own. Did you make other local changes to autotooltip to fix other bugs?

**Comment by barredespace** [comment]
Yep ! That dit it apparently : I couldn't make a tooltip stay with the new version ! So thanks !
And no, I did not make any other changes to autotooltip, but english not being my native language I may have expressed somehting else.

**Comment by barredespace** [comment]
One more word.
As your update did not show yet on my site, I just replaced script.js with the new version… But it seems to have lost the options : no more blue or small. A side effect ?

**Comment by zioth** [comment]
Thanks! I cleaned up the code a bit and broke those features. They're fixed now.

**Comment by barredespace** [comment]
You're welcome! Everything back to normal and no more ghost tooltips ! Great.
