### ISSUE TITLE
Tooltips don't show on relative links within a namespace

### ISSUE THREAD

**Issue by JohnMTurnbull** [zioth/dokuwiki-autotooltip#24]
Tooltips don't show on relative links, either with the renderer if one uses [[..:section:page]] or with <autott>..:section:page</autott>, or even within a namespace using [[page]]

**Comment by zioth** [comment]
Fixed. It looks like a lot of relative links weren't working. Good catch!

Note that this feature will only work if you have autotooltip set up as a renderer plugin, or you've installed the actionrenderer plugin. If you're not using the renderer, you'll either have to use the <autotooltip> markup, or use the autolink4 plugin to add tooltips to specific words.

**Comment by JohnMTurnbull** [comment]
Thanks for the quick fix!
