### ISSUE TITLE
Regex for INCLUDE, in addition to EXCLUDE pages

### ISSUE THREAD

**Issue by vaniwiki** [zioth/dokuwiki-autotooltip#6]
I only want pages from certain namespaces, usually 2-5 levels deep. This will make the regex's easier, rather than negative excluding...? Or if you know how, please let me also! :)

**Comment by vaniwiki** [comment]
I'll add to this point: I want to show tooltips only from certain namespace(s), and I want them to show only when certain conditions are met. But maybe now I'm being too picky. :)

**Comment by zioth** [comment]
It should be easy enough to add an include option. With both options available, you'll be able to say "include all pages that match regex1 except those that match regex2."

**Comment by zioth** [comment]
Done. Enjoy!

You could have used a negated regex, like this: `(?!whatever)`, but I prefer having two settings, so that you can more easily say "include these pages, but not those pages."
